config/routes.rb
PaginatorFIlterRails1::Application.routes.draw do
  get "main/index"
  root :to => "main#index"
  resources :zones

end

app/models/zone.rb
class Zone < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
 respond_to :json

  def index
    respond_with Zone.all
  end

  def show
    respond_with Zone.find(params[:id])
  end

  def create
    respond_with Zone.create(params[:zone])
  end

  def update
    respond_with Zone.update(params[:id], params[:zone])
  end

  def destroy
    respond_with Zone.destroy(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaginatorFIlterRails1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>
<table id='zones_table' class='table'></table>

app/views/zones/_form.html.erb
<%= form_for(@zone) do |f| %>
  <% if @zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% @zone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :site_name %><br />
    <%= f.text_field :site_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :width %><br />
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :auto_approve %><br />
    <%= f.check_box :auto_approve %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing zone</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<h1>Listing zones</h1>

<table>
  <tr>
    <th>Site name</th>
    <th>Name</th>
    <th>Width</th>
    <th>Height</th>
    <th>Auto approve</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zones.each do |zone| %>
  <tr>
    <td><%= zone.site_name %></td>
    <td><%= zone.name %></td>
    <td><%= zone.width %></td>
    <td><%= zone.height %></td>
    <td><%= zone.auto_approve %></td>
    <td><%= zone.active %></td>
    <td><%= link_to 'Show', zone %></td>
    <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
    <td><%= link_to 'Destroy', zone, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zone', new_zone_path %>

app/views/zones/new.html.erb
<h1>New zone</h1>

<%= render 'form' %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Site name:</b>
  <%= @zone.site_name %>
</p>

<p>
  <b>Name:</b>
  <%= @zone.name %>
</p>

<p>
  <b>Width:</b>
  <%= @zone.width %>
</p>

<p>
  <b>Height:</b>
  <%= @zone.height %>
</p>

<p>
  <b>Auto approve:</b>
  <%= @zone.auto_approve %>
</p>

<p>
  <b>Active:</b>
  <%= @zone.active %>
</p>


<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>